SELECT A.CAR_ID, B.CAR_TYPE,
ROUND(B.DAILY_FEE*(100-IFNULL(C.DISCOUNT_RATE,0))/100*30,0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR AS B ON A.CAR_ID = B.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON B.CAR_TYPE = C.CAR_TYPE
WHERE B.CAR_TYPE IN ('세단','SUV')
AND A.CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE START_DATE < '2022-12-01'
                    AND END_DATE >= '2022-11-01')
AND C.DURATION_TYPE = '30일 이상'
GROUP BY A.CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC