SELECT B.CAR_ID, B.CAR_TYPE, ROUND(30*DAILY_FEE*(100-DISCOUNT_RATE)/100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR AS B
ON A.CAR_ID=B.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON B.CAR_TYPE=C.CAR_TYPE
WHERE B.CAR_TYPE IN ('세단','SUV')
AND DURATION_TYPE='30일 이상'
AND B.CAR_ID NOT IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE<='2022-11-30'
                AND END_DATE>='2022-11-01')
GROUP BY CAR_ID
HAVING 500000<=FEE AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC