# SELECT A.CAR_ID, A.CAR_TYPE, DATEDIFF(B.END_DATE,B.START_DATE)+1 AS DURATION,
# CASE WHEN DURATION>=90
# THEN '90일 이상'
# WHEN DURATION>=30
# THEN '30일 이상'
# WHEN DURATION>=7
# THEN '7일 이상'
# END DURATION_TYPE
# FROM CAR_RENTAL_COMPANY_CAR AS A
# INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
# ON A.CAR_ID=B.CAR_ID
SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY