WITH RECURSIVE DATA1 AS(
SELECT 0 AS HOUR
UNION
SELECT HOUR+1
FROM DATA1
WHERE HOUR<23)

SELECT B.HOUR, IFNULL(COUNT(A.DATETIME),0) AS COUNT
FROM ANIMAL_OUTS AS A
RIGHT OUTER JOIN DATA1 AS B
ON HOUR(A.DATETIME)=B.HOUR
GROUP BY HOUR
ORDER BY HOUR ASC