WITH RECURSIVE DATA1 AS(
SELECT 0 AS HOUR
UNION
SELECT HOUR+1
FROM DATA1
WHERE HOUR<23)

SELECT A.HOUR, IFNULL(COUNT(B.ANIMAL_ID),0)
FROM DATA1 AS A
LEFT OUTER JOIN ANIMAL_OUTS AS B
ON A.HOUR=HOUR(B.DATETIME)
GROUP BY HOUR