
#RANK() OVER ( [PARTITION BY colName1 ] ORDER BY colName2 [DESC] )

WITH DATA1 AS (SELECT MEMBER_ID, RANK() OVER(ORDER BY COUNT(*) DESC) AS RANKING
FROM REST_REVIEW
GROUP BY MEMBER_ID)


SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE AS A
INNER JOIN REST_REVIEW AS B
ON A.MEMBER_ID=B.MEMBER_ID
WHERE B.MEMBER_ID IN (SELECT MEMBER_ID
                     FROM DATA1
                    WHERE RANKING=1)
ORDER BY DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') ASC, REVIEW_TEXT ASC