WITH DATA1 AS (
SELECT MEMBER_ID, RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING
FROM  REST_REVIEW
GROUP BY MEMBER_ID)

SELECT A.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS A
INNER JOIN REST_REVIEW AS B
ON A.MEMBER_ID=B.MEMBER_ID
WHERE B.MEMBER_ID IN (SELECT MEMBER_ID
                   FROM DATA1
                   WHERE RANKING=1)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC