WITH DATA1 AS (SELECT MEMBER_ID, RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING
FROM REST_REVIEW
GROUP BY MEMBER_ID)

SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW AS A
LEFT OUTER JOIN MEMBER_PROFILE AS B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID IN (SELECT MEMBER_ID
                     FROM DATA1
                     WHERE RANKING = 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT