SELECT B.AUTHOR_ID, B.AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK AS A
INNER JOIN AUTHOR AS B
ON A.AUTHOR_ID=B.AUTHOR_ID
INNER JOIN BOOK_SALES AS C
ON A.BOOK_ID=C.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-01'
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC