SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK AS A
LEFT OUTER JOIN AUTHOR AS B
ON A.AUTHOR_ID = B.AUTHOR_ID
LEFT OUTER JOIN BOOK_SALES AS C
ON A.BOOK_ID = C.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC