WITH DATA1 AS (
SELECT *, DATEDIFF(END_DATE,START_DATE)+1 AS PERIOD,
CASE WHEN DATEDIFF(END_DATE,START_DATE)+1>=90 THEN '90일 이상'
WHEN DATEDIFF(END_DATE,START_DATE)+1>=30 THEN '30일 이상'
WHEN DATEDIFF(END_DATE,START_DATE)+1>=7 THEN '7일 이상'
END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)

SELECT HISTORY_ID,
ROUND((100-IFNULL(DISCOUNT_RATE,0))/100*DAILY_FEE*PERIOD,0) AS FEE
FROM DATA1 AS A
INNER JOIN CAR_RENTAL_COMPANY_CAR AS B
ON A.CAR_ID=B.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON B.CAR_TYPE=C.CAR_TYPE
AND A.DURATION_TYPE=C.DURATION_TYPE
WHERE B.CAR_TYPE='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC