WITH DATA1 AS (
SELECT A.HISTORY_ID, A.CAR_ID, B.CAR_TYPE, B.DAILY_FEE, 
DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS PERIOD,
CASE WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 90
THEN '90일 이상'
WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 30
THEN '30일 이상'
WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 7
THEN '7일 이상'
END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR AS B ON A.CAR_ID =  B.CAR_ID)

SELECT HISTORY_ID, ROUND(DAILY_FEE * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100 * PERIOD, 0) AS FEE
FROM DATA1 AS C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
ON C.CAR_TYPE = D.CAR_TYPE AND C.DURATION_TYPE = D.DURATION_TYPE
WHERE C.CAR_TYPE ='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC