SELECT A.APNT_NO, B.PT_NAME, B.PT_NO, C.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
LEFT OUTER JOIN PATIENT AS B
ON A.PT_NO=B.PT_NO
LEFT OUTER JOIN DOCTOR AS C
ON A.MDDR_ID=C.DR_ID
WHERE DATE_FORMAT(A.APNT_YMD,'%Y-%m-%d')='2022-04-13'
AND A.APNT_CNCL_YN='N'
AND A.MCDP_CD='CS'
ORDER BY A.APNT_YMD ASC