SELECT APNT_NO, PT_NAME, B.PT_NO, C.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AS A
INNER JOIN PATIENT AS B
ON A.PT_NO=B.PT_NO
INNER JOIN DOCTOR AS C
ON A.MDDR_ID=C.DR_ID
WHERE C.MCDP_CD='CS'
AND DATE_FORMAT(APNT_YMD,'%Y-%m-%d')='2022-04-13'
AND APNT_CNCL_YMD IS NULL
ORDER BY APNT_YMD ASC